language: python
python:
  - 3.5

git:
  submodules: false

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - git submodule update --init --recursive

install:
  - docker build --build-arg QGIS_TEST_VERSION=${QGIS_TEST_VERSION} -f .docker/Dockerfile .

jobs:
  include:
    - stage: test
      env:
        QGIS_TEST_VERSION="latest"
      script: docker-compose -f .docker/docker-compose.travis.yml run qgis /usr/src/.docker/run-docker-tests.sh
    - stage: test
      env:
        QGIS_TEST_VERSION="release-3_0"
      script: docker-compose -f .docker/docker-compose.travis.yml run qgis /usr/src/.docker/run-docker-tests.sh

    - stage: deploy
      if: tag IS present
      install:
        - pip install -r requirements.txt
      script: plugin_ci/release/release.sh
    - stage: deploy
      if: branch = master
      install:
        - sudo apt-get install -y pyqt5-dev-tools
        - pip install -r requirements.txt
      script: scripts/ci/update-translations.sh

env:
  global:
    - PUSH_TO=github # plugins (osgeo login, default), github (current repo)
    - PLUGIN_AUTHOR=OPENGIS.ch

    - OSGEO_USERNAME=mkuhn
    # Inject OSGEO_PASSWORD matching the OSGEO_USERNAME
    # Generate with the following command for proper special characters support
    #     travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
    - secure: "eEt7uqkJBoJWgrDk4rwFHuL0zudEzdj+3kiANRhJXmmmeR46zVkyt3naJGIE2OjAUV3g9s06JciGNzyUxgjhl0UBj2CNqgQd1NTUWdJEiumD00geXyTnLfyz6vl0DG/S1zW9SAtCNkwHGwg6z/MedS1kODj0RApZUmq1MVE+FaremryLp61MCPVuuVslX65Te1XbfKGiQLjSa4TjRzUClL2xSHzFWmAHYIrPoib1UoS5F/BJEXCqR8bTtR9pt72V56PeV5nvReXe5fhukOylxtf3/c+bNpEM2f51tr5f2IrOMHYPD6JfpvBp1SWqdVAmx0P8iLaFa3tXTtC7HFyKhib9k6auE4u4/c4XN46beic6cKNtYkbJ4ttQg8TDA+h4y66VumoRWgJrYxv3OJLTj8SQEQCXEkdYSzpvwdnw/hi3hCkwa2Yyl9VGrcIzx3/xBQwnCZBw1sqNdEHakeKu/XogPt/0VBRzaFvDjhHofyHcOcz3z/IPPtEj9WV7nruWCkeR+kkhPZPrS1+2GnG0BfHhJh8yUSxOfcf6NUR/3BNlO3csVXU594Ct8vQ7VBiEx2Vj4BAhANBLLR1vNXr70c5v+2R5KKY/DeZwtd9cEEbY9koxIpwRwZj8ye5DpZo1+rTxNY17V0WaWIt9ZXheBx2iSlGiMSdBIYQqyyrWXZ0="
    # OAUTH_TOKEN <- personal access token for github to deploy on "releases"
    # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
    - secure: "51yV6CNJCRpQ0X66fRYT/SSbCq9AM1UFl4BlcNKMkKQ/3llcf6XWM6HVQ5wiAgZSeIut0aGun2VpmRkgSxpoORUCHERth6vDjRyIELYxcq26otfM8okWYh61H2oggiVEFp0ACMl6a3dphzsFMT+7LLDJ1o45cV49VuVbbX4Pa/3eBeSA/TVU03PZE7nSNDGRcHoZM/WTkPDEbfCr8NaF/LD5E5LPLe3XThrZPeBOkQAJP4QIrIvdLPUH7yfbjDU1PQi/ys0FbYbPzC9TiaUA5R+VcAh4J6q2Dhjtl0Q9g/GzzJUj2zF2RoGGk0AsLdRP0dxoNM4FD9pAvpEfTZZFU1xOj8PKnniM6ry5oeaNJwevIXNB6qsHVWbOHIPGzsYG7acRukZxhzOB2x8QyqmdJoVPhUvcKQ1Mypn9b0qE8f0QwtTNPJAvCIGm+iK+hnj0wuQ9+pK/YofDMBVCPdITkZ3F1OzIdg3kvvoa7lmv/HHTuKy0eqqw03+j3wMDoy0TmlfV6iHzAeYYm/mbQzUt64XfFVUJKcvv6Y2zCbfgodEEu/QZmnJJb8/qw/tTxJHp7tcVUVSxBFFYdMIFfKKqwwnh3vJgnw73YoSrtfezLTNkb4q3NqZcJ5nBkhPjZziBFUQcIuL5XSNqSfXo3WjSvSN0rgVvjBbgTccISqhOprI="
    # TX_TOKEN
    - secure: "c1BA1rfkPqTAXWL4favgF8waMrJUHADPeTLCaXWYgPL93/VJy4dzVZdzyJygPvqL+S1jnnAQhhNvqD7xaykh8GtSyGZJtApkjFbC+IoFf+ffCr/o3laG75qsfOq66sugPU3pBSvv7WGpVMxl7zbEHGMioVlRCQmc9VClgVge66Np4Le5rxAKP/+xczGYGKOEGMly24A7L/UBopWA/qqceXdLh0zCHHSldDBFmzSHchLNVoboEKy3MJwqE1vlCXv5qtgQfgnTKGDv5fowUYiimzQXRPlZLT/lYJ8ME/k/8T72/Kr/oCbpetw5SL9sIJQ8fLKUx2wgEaz97V4CMYG5pIvmYYlPwkDB0H3PWoU8Y6HV3EBpBqZ0lsQcQSe2HbKquFAohcBBV/oFkCsgywFP50OXbQxJF/d1SojUuGFFHQ1XGYMVbuoG+p8tc1gF779rR/XnJcoJx+zyx3Pu8OUh+mM4suIZeFKJtQFRnh7IVNyE7oAzUKhvdUPfHN+3e+7OCbVgnUvvU2G0KXEtl5ASQF6K98ME9fkTLggl6t/E2xsqetkGORAaziJLVUBvc8WNsGHtq8992b7z4qoKZ6Qd+nMVWXmTxSnVM9H9XaUBFjHEcDCpvc6ugIydMwvQ6oN5faKfOKM44TpetBUwlCp8sq5oFRUxryG39fwSFKMpeAg="
